spring.application.name=bus-tracking-system

server.port=${PORT:8080}


# DATABASE

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/bus_tracking_db}

spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false


# CONNECTION POOL

spring.datasource.hikari.maximum-pool-size=5

spring.datasource.hikari.minimum-idle=1


# ERROR MESSAGE

server.error.include-message=always