# APPLICATION NAME

spring.application.name=bus-tracking-system


# SERVER PORT
# Locally: uses port 8080
# Cloud: uses the port provided by the hosting platform

server.port=${PORT:8080}


# POSTGRESQL DATABASE
# Locally: uses your laptop PostgreSQL database
# Cloud: values will come from environment variables

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/bus_tracking_db}

spring.datasource.username=${DATABASE_USERNAME:postgres}

spring.datasource.password=${DATABASE_PASSWORD:admin}


# POSTGRESQL DRIVER

spring.datasource.driver-class-name=org.postgresql.Driver


# HIBERNATE

spring.jpa.hibernate.ddl-auto=update


# SQL LOGGING
# Keep false for cloud deployment

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true


# DATABASE CONNECTION SETTINGS

spring.datasource.hikari.maximum-pool-size=${DB_MAX_POOL_SIZE:5}

spring.datasource.hikari.minimum-idle=${DB_MIN_IDLE:1}


# WEBSOCKET AND LONG CONNECTION SUPPORT

server.tomcat.connection-timeout=60s


# ERROR DETAILS

server.error.include-message=always